### PR TITLE
Cart page

### PR DESCRIPTION
**Pull request by mikesch803**

### CODE REVIEW

**Comment by mikesch803** [comment]
cart page

**Review by Vishnu-Aithal — CHANGES_REQUESTED** [review]
Bulletins visible before card. Remove default list styling from Cart List.

**Comment by mikesch803** [comment]
cart page

**Comment by mikesch803** [comment]
> Bulletins visible before card. Remove default list styling from Cart List.

fixed

**Review by Vishnu-Aithal — APPROVED** [review]
No Major issues Things Looks Good!
Small Suggestions: 
- eliminate space above nav
- can decrease some white space between nav and content
- improve contrast between background with "card" and "total" elements or add small box shadows

**Review by anik31 — COMMENTED** [review]
You can add plus minus buttons for quantity counter

**Comment by mikesch803** [comment]
> No Major issues Things Looks Good! Small Suggestions:
> 
> * eliminate space above nav
> * can decrease some white space between nav and content
> * improve contrast between background with "card" and "total" elements or add small box shadows

if different items add to the cart, it will eliminate the space automatically, the only space nav and content is 1rem

**Comment by mikesch803** [comment]
> You can add plus minus buttons for quantity counter

input tag has the same thing

**Comment by anik31** [comment]
> > You can add plus minus buttons for quantity counter
> 
> input tag has the same thing

Got it

**Review by anik31 — APPROVED** [review]

**Comment by mikesch803** [comment]
https://modest-chandrasekhar-30e3d0.netlify.app/pages/cart.html

**Pull request merged**
