### PR TITLE
feat : wishlist-page

### PR DESCRIPTION
**Pull request by mikesch803**
added wishlist page

wishlist-fit-store

### CODE REVIEW

**Review by ApurvaSawant11 — APPROVED** [review]
Looks nice. Just check if adding more space before `card-price` looks good or not.

**Review by vrinda-mahajan — APPROVED** [review]
LGTM👍

**Review by abhisheksahani-nova — APPROVED** [review]
Looks good , just try adding some space between cards and also inside the content

**Review by ParthParolekar — APPROVED** [review]
Looks great! Good job

**Pull request merged**
