### PR TITLE
feat : product-page

### PR DESCRIPTION
**Pull request by mikesch803**

### CODE REVIEW

**Comment by mikesch803** [comment]
live link  https://modest-chandrasekhar-30e3d0.netlify.app/pages/product.html

**Review by vrx29 — COMMENTED** [review]
Code looks good. Please reduce the font-size of price in product card and align it properly

**Comment by mikesch803** [comment]
> Code looks good. Please reduce the font-size of price in product card and align it properly

I reduced its font size but the alignment issue because of font family

**Review by vrx29 — APPROVED** [review]

**Comment by hsnice16** [comment]
UI looks nice, very clean. Just three suggestions,

1. Give some space between cards, as on hovering due to shadow It is not looking good.
2. On the hover of ADD TO CART and WISHLIST just apply some dark shade of the same `background color`. Right now, it is black I think, and it is not looking good.
3. Give `cursor pointer` to checkboxes and radio.

**Comment by mikesch803** [comment]
> UI looks nice, very clean. Just three suggestions,
> 
> 1. Give some space between cards, as on hovering due to shadow It is not looking good.
> 2. On the hover of ADD TO CART and WISHLIST just apply some dark shade of the same `background color`. Right now, it is black I think, and it is not looking good.
> 3. Give `cursor pointer` to checkboxes and radio.

first and last thing I changed but hover effect will change from CL

**Review by hsnice16 — APPROVED** [review]

**Pull request merged**
